pkg/deb/debian: Upgrade debian packaging.

diff --git a/pkg/deb/debian/sems.init b/pkg/deb/debian/sems.init
--- a/pkg/deb/debian/sems.init
+++ b/pkg/deb/debian/sems.init
@@ -8,10 +8,17 @@
 # Short-Description: Start/stop SEMS Application Server
 ### END INIT INFO
 
+. /lib/lsb/init-functions
 
 # read configuration from /etc/default/sems file
 if test -f /etc/default/sems ; then
   . /etc/default/sems
+fi
+
+
+if test "$SEMS_RUN" = "no" ; then
+    log_failure_msg "Sems start disabled by default file"
+    exit 0
 fi
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -20,6 +27,11 @@ NAME=sems
 DESC=sems
 
 PARAMS=""
+
+if ! test -d $SEMS_RUNDIR ; then
+   mkdir $SEMS_RUNDIR
+fi
+chown $SEMS_USER:$SEMS_GROUP $SEMS_RUNDIR
 
 if test "$SEMS_PIDFILE" ; then
   PARAMS="$PARAMS -P $SEMS_PIDFILE"
@@ -43,18 +55,16 @@ if test "$SEMS_CREATE_CORE" = "yes" ; then
 	[ -d $SEMS_COREDIR ] || mkdir $SEMS_COREDIR
 	chmod 777 $SEMS_COREDIR
 	echo "$SEMS_COREDIR/core.%e.sig%s.%p" > /proc/sys/kernel/core_pattern
+	echo 2 > /proc/sys/fs/suid_dumpable
 	ulimit -c unlimited
 fi
 
-if ! test -f $DAEMON ; then
-  echo "Error: cannot find $DAEMON"
-  exit 0
-fi
+# raise file descriptors limit - call hold consumes two fds for RTP ports and one for moh file
+ulimit -n 100000
 
-# /var/run can be a tmpfs
-if [ ! -d $HOMEDIR ]; then
-    mkdir -p $HOMEDIR
-    chown $SEMS_USER:$SEMS_GROUP $HOMEDIR
+if ! test -f $DAEMON ; then
+  log_failure_msg "Error: cannot find $DAEMON"
+  exit 1
 fi
 
 LD_LIBRARY_PATH=/usr/lib/sems
@@ -62,49 +72,21 @@ export LD_LIBRARY_PATH
 
 set -e
 
-. /lib/lsb/init-functions
-
 case "$1" in
   start)
-	echo "Starting $DESC: $NAME"
+	log_daemon_msg "Starting $DESC: $NAME "
 	start-stop-daemon --start --quiet --oknodo --pidfile $SEMS_PIDFILE \
 		--exec $DAEMON -- $PARAMS
 	log_end_msg $?
 	;;
   stop)
-	echo -n "Stopping $DESC: $NAME"
+	log_daemon_msg "Stopping $DESC: $NAME "
 	start-stop-daemon --oknodo --stop --quiet --pidfile $SEMS_PIDFILE \
 		--exec $DAEMON
 	log_end_msg $?
 	;;
-  #reload)
-	#
-	#	If the daemon can reload its config files on the fly
-	#	for example by sending it SIGHUP, do it here.
-	#
-	#	If the daemon responds to changes in its config file
-	#	directly anyway, make this a do-nothing entry.
-	#
-	# echo "Reloading $DESC configuration files."
-	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
-	#	$SEMS_PIDFILE --exec $DAEMON
-  #;;
   restart|force-reload)
-	#
-	#	If the "reload" option is implemented, move the "force-reload"
-	#	option to the "reload" entry above. If not, "force-reload" is
-	#	just the same as "restart".
-	#
-	# Check if configuration is valid before restarting the server
-        #(($DAEMON $CFGPARAMS -c 2>&1) | grep "config file ok, exiting") > /dev/null
-	#if [ $? -ne 0 ]; then
-        #    ($DAEMON $CFGPARAMS -c 2>&1)
-	#    echo -e "\nThere are errors in the configuration file. Please fix them first"
-	#    echo -e "\n$out\n"
-	#    exit 0
-	#fi
-	
-	echo "Restarting $DESC: $NAME"
+	log_daemon_msg "Restarting $DESC: $NAME "
 	start-stop-daemon --oknodo --stop --quiet --pidfile \
 		$SEMS_PIDFILE --exec $DAEMON
 	sleep 5
@@ -117,7 +99,6 @@ case "$1" in
        ;;
   *)
 	N=/etc/init.d/$NAME
-	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
 	exit 1
 	;;
